# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bcb9a17010490bd6be246b395d2dcbef"
name = "drum-test-app"
handle = "drum-test-app"
application_url = "https://wins-solving-ping-soil.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore3222.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wins-solving-ping-soil.trycloudflare.com/auth/callback",
  "https://wins-solving-ping-soil.trycloudflare.com/auth/shopify/callback",
  "https://wins-solving-ping-soil.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
